version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true #uncomment for development in local
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./ssl:/ssl:ro
    networks:
      - traefik-network
      # - migrate-cars-form-app_default
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    environment:
      - TZ=Asia/Bangkok

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
  migrate-cars-form-app_default:
    external: true
